### ISSUE TITLE
node mina.js 出错，请问如何解决？

### ISSUE THREAD

**Issue by yorkbbs** [buqiyuan/nest-admin#26] opened 2024-02-08 04:43 UTC
[Nest] 15984  - 2024/02/08 11:25:38     LOG [InstanceLoader] SharedModule dependencies initialized +1ms
[Nest] 15984  - 2024/02/08 11:25:38     LOG [InstanceLoader] MailerModule dependencies initialized +0ms
[Nest] 15984  - 2024/02/08 11:25:38     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 15984  - 2024/02/08 11:25:38     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
[Nest] 15984  - 2024/02/08 11:25:38     LOG [InstanceLoader] SystemModule dependencies initialized +0ms
[Nest] 15984  - 2024/02/08 11:25:38     LOG [InstanceLoader] HttpModule dependencies initialized +0ms
[Nest] 15984  - 2024/02/08 11:25:38     LOG [InstanceLoader] ThrottlerModule dependencies initialized +1ms
[Nest] 15984  - 2024/02/08 11:25:38     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 15984  - 2024/02/08 11:25:38     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 15984  - 2024/02/08 11:25:38     LOG [InstanceLoader] RouterModule dependencies initialized +0ms
[Nest] 15984  - 2024/02/08 11:25:38     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 15984  - 2024/02/08 11:25:38     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 15984  - 2024/02/08 11:25:38   ERROR [ExceptionHandler] JwtStrategy requires a secret or key
TypeError: JwtStrategy requires a secret or key
    at new JwtStrategy (E:\dev\YorkPorn\nest-admin-main2\node_modules\.pnpm\passport-jwt@4.0.1\node_modules\passport-jwt\lib\strategy.js:45:15)
    at new MixinStrategy (E:\dev\YorkPorn\nest-admin-main2\node_modules\.pnpm\@nestjs+passport@10.0.3_@nestjs+common@10.3.2_passport@0.7.0\node_modules\@nestjs\passport\dist\passport\passport.strategy.js:32:13)
    at new JwtStrategy (E:\dev\YorkPorn\nest-admin-main2\dist\modules\auth\strategies\jwt.strategy.js:24:9)
    at Injector.instantiateClass (E:\dev\YorkPorn\nest-admin-main2\node_modules\.pnpm\@nestjs+core@10.3.2_@nestjs+common@10.3.2_@nestjs+websockets@10.3.2_reflect-metadata@0.2.1_rxjs@7.8.1\node_modules\@nestjs\core\injector\injector.js:365:19)
    at callback (E:\dev\YorkPorn\nest-admin-main2\node_modules\.pnpm\@nestjs+core@10.3.2_@nestjs+common@10.3.2_@nestjs+websockets@10.3.2_reflect-metadata@0.2.1_rxjs@7.8.1\node_modules\@nestjs\core\injector\injector.js:65:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Injector.resolveConstructorParams (E:\dev\YorkPorn\nest-admin-main2\node_modules\.pnpm\@nestjs+core@10.3.2_@nestjs+common@10.3.2_@nestjs+websockets@10.3.2_reflect-metadata@0.2.1_rxjs@7.8.1\node_modules\@nestjs\core\injector\injector.js:144:24)
    at async Injector.loadInstance (E:\dev\YorkPorn\nest-admin-main2\node_modules\.pnpm\@nestjs+core@10.3.2_@nestjs+common@10.3.2_@nestjs+websockets@10.3.2_reflect-metadata@0.2.1_rxjs@7.8.1\node_modules\@nestjs\core\injector\injector.js:70:13)
    at async Injector.loadProvider (E:\dev\YorkPorn\nest-admin-main2\node_modules\.pnpm\@nestjs+core@10.3.2_@nestjs+common@10.3.2_@nestjs+websockets@10.3.2_reflect-metadata@0.2.1_rxjs@7.8.1\node_modules\@nestjs\core\injector\injector.js:97:9)
    at async E:\dev\YorkPorn\nest-admin-main2\node_modules\.pnpm\@nestjs+core@10.3.2_@nestjs+common@10.3.2_@nestjs+websockets@10.3.2_reflect-metadata@0.2.1_rxjs@7.8.1\node_modules\@nestjs\core\injector\instance-loader.js:56:13

**Comment by buqiyuan** [comment] 2024-02-08 04:48
Duplicate of #24

**Comment by yorkbbs** [comment] 2024-02-08 07:42
thanks

**Closed** 2024-02-08 07:41 UTC
